---
services:
  traefik:
    image: traefik:v3.4
    user: root
    # release notes: https://github.com/traefik/traefik/releases
    networks:
      freshcap-net:
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL:-ERROR}"
      # letsencrypt configuration
      - "--certificatesResolvers.http.acme.email=${TRAEFIK_ACME_MAIL:-example@example.org}"
      - "--certificatesResolvers.http.acme.storage=/certs/acme.json"
      - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=http"
      - "--certificatesResolvers.http.acme.caserver=${TRAEFIK_ACME_CASERVER:-https://acme-v02.api.letsencrypt.org/directory}"
      # enable dashboard
      - "--api.dashboard=true"
      # define entrypoints
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.http.redirections.entryPoint.to=https"
      - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.https.address=:443"
      # change default timeouts for long-running requests
      # this is needed for webdav clients that do not support the TUS protocol
      - "--entryPoints.https.transport.respondingTimeouts.readTimeout=12h"
      - "--entryPoints.https.transport.respondingTimeouts.writeTimeout=12h"
      - "--entryPoints.https.transport.respondingTimeouts.idleTimeout=3m"
      # docker provider (get configuration from container labels)
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      # access log
      - "--accessLog=true"
      - "--accessLog.format=json"
      - "--accessLog.fields.headers.names.X-Request-Id=keep"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock:ro"
      - "certs:/certs"
    labels:
      - "traefik.enable=${TRAEFIK_DASHBOARD:-false}"
       # defaults to admin:admin
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH_USERS:-admin:$$apr1$$4vqie50r$$YQAmQdtmz5n9rEALhxJ4l.}"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN:-traefik.opencloud.test}`)"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.tls.certresolver=http"
      - "traefik.http.routers.traefik.service=api@internal"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

  formdrop:
    image: ghcr.io/freshcap-at/formdrop:main
    container_name: "formdrop"
    networks:
      - freshcap-net
    environment:
      CAP_INSTANCE_URL: "https://captcha.freshcap.at/"
      CAP_CAPTCHA_TOKEN: ""
      MAIL_USERNAME: "no-reply@freshcap.at"
      MAIL_PASSWORD: "anypwd"
      MAIL_FROM: "no-reply@freshcap.at"
      MAIL_PORT: 587
      MAIL_SERVER: mail.your-server.de
      MAIL_FROM_NAME: "webtools by freshcap.at"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3001/"]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - formdrop:/code/storage
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=freshcap-net"
      - "traefik.http.routers.formdrop.entrypoints=https"
      - "traefik.http.routers.formdrop.rule=(Host(`forms.freshcap.at`))"
      - "traefik.http.routers.formdrop.tls.certresolver=http"
      - "traefik.http.services.formdrop.loadbalancer.server.port=3001"

  capjs:
    image: tiago2/cap:latest
    container_name: "capjs"
    networks:
      - freshcap-net
    environment:
      ADMIN_KEY: "myawesomekey"
      ENABLE_ASSETS_SERVER: "false"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/"]
      interval: 300s
      timeout: 5s
      retries: 5
    volumes:
      - capjs:/usr/src/app/.data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=freshcap-net"
      - "traefik.http.routers.formdrop.entrypoints=https"
      - "traefik.http.routers.formdrop.rule=(Host(`captcha.freshcap.at`))"
      - "traefik.http.routers.formdrop.tls.certresolver=http"
      - "traefik.http.services.formdrop.loadbalancer.server.port=3000"

volumes:
  certs:
  formdrop:
  capjs:

networks:
  freshcap-net: